/* GENERATED by tools/build-pdfs.mjs. Do not edit.
   Wspolrzedne kazdego pola na PUSTYM formularzu, w punktach PDF liczonych od lewego
   dolnego rogu strony. Zmierzone w ukladzie DRUKU przez Chrome — patrz measureFields()
   w generatorze. Uzywa ich worker/fill-form.js, zeby dopisac dane na gotowej stronie. */
/* eslint-disable */
export const FORM_FIELDS = {
 "Carruleddhi-modulo-it": {
  "RACE_NUMBER": {
   "x": 509.35,
   "y": 774.67,
   "width": 36.25,
   "size": 21
  },
  "FULL_NAME": {
   "x": 34.02,
   "y": 694.1,
   "width": 252.28,
   "size": 10
  },
  "BIRTH_DATE": {
   "x": 308.97,
   "y": 694.1,
   "width": 252.29,
   "size": 10
  },
  "POSTAL_CODE": {
   "x": 34.02,
   "y": 661.72,
   "width": 252.28,
   "size": 10
  },
  "PHONE": {
   "x": 308.97,
   "y": 661.72,
   "width": 252.29,
   "size": 10
  },
  "EMAIL": {
   "x": 34.02,
   "y": 629.34,
   "width": 252.28,
   "size": 10
  },
  "ADDRESS": {
   "x": 308.97,
   "y": 629.34,
   "width": 252.29,
   "size": 10
  },
  "CART_NAME": {
   "x": 34.02,
   "y": 570.59,
   "width": 252.28,
   "size": 10
  },
  "CATEGORY": {
   "x": 308.97,
   "y": 570.59,
   "width": 252.29,
   "size": 10
  },
  "TEAM": {
   "x": 34.02,
   "y": 538.21,
   "width": 252.28,
   "size": 10
  },
  "CART_NOTES": {
   "x": 308.97,
   "y": 538.21,
   "width": 252.29,
   "size": 10
  }
 },
 "Carruleddhi-minori-it": {
  "RACE_NUMBER": {
   "x": 522.42,
   "y": 777.31,
   "width": 28.76,
   "size": 16
  },
  "FULL_NAME": {
   "x": 153.07,
   "y": 728.31,
   "width": 413.78,
   "size": 8
  },
  "BIRTH_DATE": {
   "x": 153.07,
   "y": 714,
   "width": 413.78,
   "size": 8
  },
  "RIDER_AGE": {
   "x": 153.07,
   "y": 699.69,
   "width": 413.78,
   "size": 8
  },
  "POSTAL_CODE": {
   "x": 153.07,
   "y": 685.38,
   "width": 413.78,
   "size": 8
  },
  "ADDRESS": {
   "x": 153.07,
   "y": 671.07,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_NAME": {
   "x": 153.07,
   "y": 638.52,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_RELATION": {
   "x": 153.07,
   "y": 624.21,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_EMAIL": {
   "x": 153.07,
   "y": 609.9,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_PHONE": {
   "x": 153.07,
   "y": 595.59,
   "width": 413.78,
   "size": 8
  },
  "MOTHER_NAME": {
   "x": 153.07,
   "y": 581.29,
   "width": 413.78,
   "size": 8
  },
  "FATHER_NAME": {
   "x": 153.07,
   "y": 566.98,
   "width": 413.78,
   "size": 8
  },
  "CART_NAME": {
   "x": 153.07,
   "y": 516.96,
   "width": 413.78,
   "size": 8
  },
  "CATEGORY": {
   "x": 153.07,
   "y": 502.65,
   "width": 413.78,
   "size": 8
  },
  "TEAM": {
   "x": 153.07,
   "y": 488.34,
   "width": 413.78,
   "size": 8
  },
  "CART_NOTES": {
   "x": 153.07,
   "y": 474.04,
   "width": 413.78,
   "size": 8
  }
 },
 "Carruleddhi-modulo-pl": {
  "RACE_NUMBER": {
   "x": 509.35,
   "y": 734.13,
   "width": 36.25,
   "size": 21
  },
  "FULL_NAME": {
   "x": 34.02,
   "y": 653.55,
   "width": 252.28,
   "size": 10
  },
  "BIRTH_DATE": {
   "x": 308.97,
   "y": 653.55,
   "width": 252.29,
   "size": 10
  },
  "POSTAL_CODE": {
   "x": 34.02,
   "y": 621.17,
   "width": 252.28,
   "size": 10
  },
  "PHONE": {
   "x": 308.97,
   "y": 621.17,
   "width": 252.29,
   "size": 10
  },
  "EMAIL": {
   "x": 34.02,
   "y": 588.79,
   "width": 252.28,
   "size": 10
  },
  "ADDRESS": {
   "x": 308.97,
   "y": 588.79,
   "width": 252.29,
   "size": 10
  },
  "CART_NAME": {
   "x": 34.02,
   "y": 530.04,
   "width": 252.28,
   "size": 10
  },
  "CATEGORY": {
   "x": 308.97,
   "y": 530.04,
   "width": 252.29,
   "size": 10
  },
  "TEAM": {
   "x": 34.02,
   "y": 497.67,
   "width": 252.28,
   "size": 10
  },
  "CART_NOTES": {
   "x": 308.97,
   "y": 497.67,
   "width": 252.29,
   "size": 10
  }
 },
 "Carruleddhi-minori-pl": {
  "RACE_NUMBER": {
   "x": 522.42,
   "y": 751.47,
   "width": 28.76,
   "size": 16
  },
  "FULL_NAME": {
   "x": 153.07,
   "y": 702.47,
   "width": 413.78,
   "size": 8
  },
  "BIRTH_DATE": {
   "x": 153.07,
   "y": 688.16,
   "width": 413.78,
   "size": 8
  },
  "RIDER_AGE": {
   "x": 153.07,
   "y": 673.85,
   "width": 413.78,
   "size": 8
  },
  "POSTAL_CODE": {
   "x": 153.07,
   "y": 659.54,
   "width": 413.78,
   "size": 8
  },
  "ADDRESS": {
   "x": 153.07,
   "y": 645.23,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_NAME": {
   "x": 153.07,
   "y": 612.68,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_RELATION": {
   "x": 153.07,
   "y": 598.37,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_EMAIL": {
   "x": 153.07,
   "y": 584.06,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_PHONE": {
   "x": 153.07,
   "y": 569.75,
   "width": 413.78,
   "size": 8
  },
  "MOTHER_NAME": {
   "x": 153.07,
   "y": 555.45,
   "width": 413.78,
   "size": 8
  },
  "FATHER_NAME": {
   "x": 153.07,
   "y": 541.14,
   "width": 413.78,
   "size": 8
  },
  "CART_NAME": {
   "x": 153.07,
   "y": 491.12,
   "width": 413.78,
   "size": 8
  },
  "CATEGORY": {
   "x": 153.07,
   "y": 476.81,
   "width": 413.78,
   "size": 8
  },
  "TEAM": {
   "x": 153.07,
   "y": 462.5,
   "width": 413.78,
   "size": 8
  },
  "CART_NOTES": {
   "x": 153.07,
   "y": 448.2,
   "width": 413.78,
   "size": 8
  }
 },
 "Carruleddhi-modulo-en": {
  "RACE_NUMBER": {
   "x": 509.35,
   "y": 734.13,
   "width": 36.25,
   "size": 21
  },
  "FULL_NAME": {
   "x": 34.02,
   "y": 653.55,
   "width": 252.28,
   "size": 10
  },
  "BIRTH_DATE": {
   "x": 308.97,
   "y": 653.55,
   "width": 252.29,
   "size": 10
  },
  "POSTAL_CODE": {
   "x": 34.02,
   "y": 621.17,
   "width": 252.28,
   "size": 10
  },
  "PHONE": {
   "x": 308.97,
   "y": 621.17,
   "width": 252.29,
   "size": 10
  },
  "EMAIL": {
   "x": 34.02,
   "y": 588.79,
   "width": 252.28,
   "size": 10
  },
  "ADDRESS": {
   "x": 308.97,
   "y": 588.79,
   "width": 252.29,
   "size": 10
  },
  "CART_NAME": {
   "x": 34.02,
   "y": 530.04,
   "width": 252.28,
   "size": 10
  },
  "CATEGORY": {
   "x": 308.97,
   "y": 530.04,
   "width": 252.29,
   "size": 10
  },
  "TEAM": {
   "x": 34.02,
   "y": 497.67,
   "width": 252.28,
   "size": 10
  },
  "CART_NOTES": {
   "x": 308.97,
   "y": 497.67,
   "width": 252.29,
   "size": 10
  }
 },
 "Carruleddhi-minori-en": {
  "RACE_NUMBER": {
   "x": 522.42,
   "y": 751.47,
   "width": 28.76,
   "size": 16
  },
  "FULL_NAME": {
   "x": 153.07,
   "y": 702.47,
   "width": 413.78,
   "size": 8
  },
  "BIRTH_DATE": {
   "x": 153.07,
   "y": 688.16,
   "width": 413.78,
   "size": 8
  },
  "RIDER_AGE": {
   "x": 153.07,
   "y": 673.85,
   "width": 413.78,
   "size": 8
  },
  "POSTAL_CODE": {
   "x": 153.07,
   "y": 659.54,
   "width": 413.78,
   "size": 8
  },
  "ADDRESS": {
   "x": 153.07,
   "y": 645.23,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_NAME": {
   "x": 153.07,
   "y": 612.68,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_RELATION": {
   "x": 153.07,
   "y": 598.37,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_EMAIL": {
   "x": 153.07,
   "y": 584.06,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_PHONE": {
   "x": 153.07,
   "y": 569.75,
   "width": 413.78,
   "size": 8
  },
  "MOTHER_NAME": {
   "x": 153.07,
   "y": 555.45,
   "width": 413.78,
   "size": 8
  },
  "FATHER_NAME": {
   "x": 153.07,
   "y": 541.14,
   "width": 413.78,
   "size": 8
  },
  "CART_NAME": {
   "x": 153.07,
   "y": 491.12,
   "width": 413.78,
   "size": 8
  },
  "CATEGORY": {
   "x": 153.07,
   "y": 476.81,
   "width": 413.78,
   "size": 8
  },
  "TEAM": {
   "x": 153.07,
   "y": 462.5,
   "width": 413.78,
   "size": 8
  },
  "CART_NOTES": {
   "x": 153.07,
   "y": 448.2,
   "width": 413.78,
   "size": 8
  }
 },
 "Carruleddhi-modulo-de": {
  "RACE_NUMBER": {
   "x": 509.35,
   "y": 722.07,
   "width": 36.25,
   "size": 21
  },
  "FULL_NAME": {
   "x": 34.02,
   "y": 641.49,
   "width": 252.28,
   "size": 10
  },
  "BIRTH_DATE": {
   "x": 308.97,
   "y": 641.49,
   "width": 252.29,
   "size": 10
  },
  "POSTAL_CODE": {
   "x": 34.02,
   "y": 609.11,
   "width": 252.28,
   "size": 10
  },
  "PHONE": {
   "x": 308.97,
   "y": 609.11,
   "width": 252.29,
   "size": 10
  },
  "EMAIL": {
   "x": 34.02,
   "y": 576.73,
   "width": 252.28,
   "size": 10
  },
  "ADDRESS": {
   "x": 308.97,
   "y": 576.73,
   "width": 252.29,
   "size": 10
  },
  "CART_NAME": {
   "x": 34.02,
   "y": 517.99,
   "width": 252.28,
   "size": 10
  },
  "CATEGORY": {
   "x": 308.97,
   "y": 517.99,
   "width": 252.29,
   "size": 10
  },
  "TEAM": {
   "x": 34.02,
   "y": 485.61,
   "width": 252.28,
   "size": 10
  },
  "CART_NOTES": {
   "x": 308.97,
   "y": 485.61,
   "width": 252.29,
   "size": 10
  }
 },
 "Carruleddhi-minori-de": {
  "RACE_NUMBER": {
   "x": 522.42,
   "y": 741.27,
   "width": 28.76,
   "size": 16
  },
  "FULL_NAME": {
   "x": 153.07,
   "y": 692.27,
   "width": 413.78,
   "size": 8
  },
  "BIRTH_DATE": {
   "x": 153.07,
   "y": 677.97,
   "width": 413.78,
   "size": 8
  },
  "RIDER_AGE": {
   "x": 153.07,
   "y": 663.66,
   "width": 413.78,
   "size": 8
  },
  "POSTAL_CODE": {
   "x": 153.07,
   "y": 649.35,
   "width": 413.78,
   "size": 8
  },
  "ADDRESS": {
   "x": 153.07,
   "y": 635.04,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_NAME": {
   "x": 153.07,
   "y": 602.48,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_RELATION": {
   "x": 153.07,
   "y": 588.18,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_EMAIL": {
   "x": 153.07,
   "y": 573.87,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_PHONE": {
   "x": 153.07,
   "y": 559.56,
   "width": 413.78,
   "size": 8
  },
  "MOTHER_NAME": {
   "x": 153.07,
   "y": 545.25,
   "width": 413.78,
   "size": 8
  },
  "FATHER_NAME": {
   "x": 153.07,
   "y": 530.94,
   "width": 413.78,
   "size": 8
  },
  "CART_NAME": {
   "x": 153.07,
   "y": 480.93,
   "width": 413.78,
   "size": 8
  },
  "CATEGORY": {
   "x": 153.07,
   "y": 466.62,
   "width": 413.78,
   "size": 8
  },
  "TEAM": {
   "x": 153.07,
   "y": 452.31,
   "width": 413.78,
   "size": 8
  },
  "CART_NOTES": {
   "x": 153.07,
   "y": 438,
   "width": 413.78,
   "size": 8
  }
 },
 "Carruleddhi-modulo-es": {
  "RACE_NUMBER": {
   "x": 509.35,
   "y": 734.13,
   "width": 36.25,
   "size": 21
  },
  "FULL_NAME": {
   "x": 34.02,
   "y": 653.55,
   "width": 252.28,
   "size": 10
  },
  "BIRTH_DATE": {
   "x": 308.97,
   "y": 653.55,
   "width": 252.29,
   "size": 10
  },
  "POSTAL_CODE": {
   "x": 34.02,
   "y": 621.17,
   "width": 252.28,
   "size": 10
  },
  "PHONE": {
   "x": 308.97,
   "y": 621.17,
   "width": 252.29,
   "size": 10
  },
  "EMAIL": {
   "x": 34.02,
   "y": 588.79,
   "width": 252.28,
   "size": 10
  },
  "ADDRESS": {
   "x": 308.97,
   "y": 588.79,
   "width": 252.29,
   "size": 10
  },
  "CART_NAME": {
   "x": 34.02,
   "y": 530.04,
   "width": 252.28,
   "size": 10
  },
  "CATEGORY": {
   "x": 308.97,
   "y": 530.04,
   "width": 252.29,
   "size": 10
  },
  "TEAM": {
   "x": 34.02,
   "y": 497.67,
   "width": 252.28,
   "size": 10
  },
  "CART_NOTES": {
   "x": 308.97,
   "y": 497.67,
   "width": 252.29,
   "size": 10
  }
 },
 "Carruleddhi-minori-es": {
  "RACE_NUMBER": {
   "x": 522.42,
   "y": 741.27,
   "width": 28.76,
   "size": 16
  },
  "FULL_NAME": {
   "x": 153.07,
   "y": 692.27,
   "width": 413.78,
   "size": 8
  },
  "BIRTH_DATE": {
   "x": 153.07,
   "y": 677.97,
   "width": 413.78,
   "size": 8
  },
  "RIDER_AGE": {
   "x": 153.07,
   "y": 663.66,
   "width": 413.78,
   "size": 8
  },
  "POSTAL_CODE": {
   "x": 153.07,
   "y": 649.35,
   "width": 413.78,
   "size": 8
  },
  "ADDRESS": {
   "x": 153.07,
   "y": 635.04,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_NAME": {
   "x": 153.07,
   "y": 602.48,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_RELATION": {
   "x": 153.07,
   "y": 588.18,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_EMAIL": {
   "x": 153.07,
   "y": 573.87,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_PHONE": {
   "x": 153.07,
   "y": 559.56,
   "width": 413.78,
   "size": 8
  },
  "MOTHER_NAME": {
   "x": 153.07,
   "y": 545.25,
   "width": 413.78,
   "size": 8
  },
  "FATHER_NAME": {
   "x": 153.07,
   "y": 530.94,
   "width": 413.78,
   "size": 8
  },
  "CART_NAME": {
   "x": 153.07,
   "y": 480.93,
   "width": 413.78,
   "size": 8
  },
  "CATEGORY": {
   "x": 153.07,
   "y": 466.62,
   "width": 413.78,
   "size": 8
  },
  "TEAM": {
   "x": 153.07,
   "y": 452.31,
   "width": 413.78,
   "size": 8
  },
  "CART_NOTES": {
   "x": 153.07,
   "y": 438,
   "width": 413.78,
   "size": 8
  }
 },
 "Carruleddhi-modulo-fr": {
  "RACE_NUMBER": {
   "x": 509.35,
   "y": 734.13,
   "width": 36.25,
   "size": 21
  },
  "FULL_NAME": {
   "x": 34.02,
   "y": 653.55,
   "width": 252.28,
   "size": 10
  },
  "BIRTH_DATE": {
   "x": 308.97,
   "y": 653.55,
   "width": 252.29,
   "size": 10
  },
  "POSTAL_CODE": {
   "x": 34.02,
   "y": 621.17,
   "width": 252.28,
   "size": 10
  },
  "PHONE": {
   "x": 308.97,
   "y": 621.17,
   "width": 252.29,
   "size": 10
  },
  "EMAIL": {
   "x": 34.02,
   "y": 588.79,
   "width": 252.28,
   "size": 10
  },
  "ADDRESS": {
   "x": 308.97,
   "y": 588.79,
   "width": 252.29,
   "size": 10
  },
  "CART_NAME": {
   "x": 34.02,
   "y": 530.04,
   "width": 252.28,
   "size": 10
  },
  "CATEGORY": {
   "x": 308.97,
   "y": 530.04,
   "width": 252.29,
   "size": 10
  },
  "TEAM": {
   "x": 34.02,
   "y": 497.67,
   "width": 252.28,
   "size": 10
  },
  "CART_NOTES": {
   "x": 308.97,
   "y": 497.67,
   "width": 252.29,
   "size": 10
  }
 },
 "Carruleddhi-minori-fr": {
  "RACE_NUMBER": {
   "x": 522.42,
   "y": 751.47,
   "width": 28.76,
   "size": 16
  },
  "FULL_NAME": {
   "x": 153.07,
   "y": 702.47,
   "width": 413.78,
   "size": 8
  },
  "BIRTH_DATE": {
   "x": 153.07,
   "y": 688.16,
   "width": 413.78,
   "size": 8
  },
  "RIDER_AGE": {
   "x": 153.07,
   "y": 673.85,
   "width": 413.78,
   "size": 8
  },
  "POSTAL_CODE": {
   "x": 153.07,
   "y": 659.54,
   "width": 413.78,
   "size": 8
  },
  "ADDRESS": {
   "x": 153.07,
   "y": 645.23,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_NAME": {
   "x": 153.07,
   "y": 612.68,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_RELATION": {
   "x": 153.07,
   "y": 598.37,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_EMAIL": {
   "x": 153.07,
   "y": 584.06,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_PHONE": {
   "x": 153.07,
   "y": 569.75,
   "width": 413.78,
   "size": 8
  },
  "MOTHER_NAME": {
   "x": 153.07,
   "y": 555.45,
   "width": 413.78,
   "size": 8
  },
  "FATHER_NAME": {
   "x": 153.07,
   "y": 541.14,
   "width": 413.78,
   "size": 8
  },
  "CART_NAME": {
   "x": 153.07,
   "y": 491.12,
   "width": 413.78,
   "size": 8
  },
  "CATEGORY": {
   "x": 153.07,
   "y": 476.81,
   "width": 413.78,
   "size": 8
  },
  "TEAM": {
   "x": 153.07,
   "y": 462.5,
   "width": 413.78,
   "size": 8
  },
  "CART_NOTES": {
   "x": 153.07,
   "y": 448.2,
   "width": 413.78,
   "size": 8
  }
 },
 "Carruleddhi-modulo": {
  "RACE_NUMBER": {
   "x": 509.35,
   "y": 774.67,
   "width": 36.25,
   "size": 21
  },
  "FULL_NAME": {
   "x": 34.02,
   "y": 694.1,
   "width": 252.28,
   "size": 10
  },
  "BIRTH_DATE": {
   "x": 308.97,
   "y": 694.1,
   "width": 252.29,
   "size": 10
  },
  "POSTAL_CODE": {
   "x": 34.02,
   "y": 661.72,
   "width": 252.28,
   "size": 10
  },
  "PHONE": {
   "x": 308.97,
   "y": 661.72,
   "width": 252.29,
   "size": 10
  },
  "EMAIL": {
   "x": 34.02,
   "y": 629.34,
   "width": 252.28,
   "size": 10
  },
  "ADDRESS": {
   "x": 308.97,
   "y": 629.34,
   "width": 252.29,
   "size": 10
  },
  "CART_NAME": {
   "x": 34.02,
   "y": 570.59,
   "width": 252.28,
   "size": 10
  },
  "CATEGORY": {
   "x": 308.97,
   "y": 570.59,
   "width": 252.29,
   "size": 10
  },
  "TEAM": {
   "x": 34.02,
   "y": 538.21,
   "width": 252.28,
   "size": 10
  },
  "CART_NOTES": {
   "x": 308.97,
   "y": 538.21,
   "width": 252.29,
   "size": 10
  }
 },
 "Carruleddhi-modulo-minori": {
  "RACE_NUMBER": {
   "x": 522.42,
   "y": 777.31,
   "width": 28.76,
   "size": 16
  },
  "FULL_NAME": {
   "x": 153.07,
   "y": 728.31,
   "width": 413.78,
   "size": 8
  },
  "BIRTH_DATE": {
   "x": 153.07,
   "y": 714,
   "width": 413.78,
   "size": 8
  },
  "RIDER_AGE": {
   "x": 153.07,
   "y": 699.69,
   "width": 413.78,
   "size": 8
  },
  "POSTAL_CODE": {
   "x": 153.07,
   "y": 685.38,
   "width": 413.78,
   "size": 8
  },
  "ADDRESS": {
   "x": 153.07,
   "y": 671.07,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_NAME": {
   "x": 153.07,
   "y": 638.52,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_RELATION": {
   "x": 153.07,
   "y": 624.21,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_EMAIL": {
   "x": 153.07,
   "y": 609.9,
   "width": 413.78,
   "size": 8
  },
  "GUARDIAN_PHONE": {
   "x": 153.07,
   "y": 595.59,
   "width": 413.78,
   "size": 8
  },
  "MOTHER_NAME": {
   "x": 153.07,
   "y": 581.29,
   "width": 413.78,
   "size": 8
  },
  "FATHER_NAME": {
   "x": 153.07,
   "y": 566.98,
   "width": 413.78,
   "size": 8
  },
  "CART_NAME": {
   "x": 153.07,
   "y": 516.96,
   "width": 413.78,
   "size": 8
  },
  "CATEGORY": {
   "x": 153.07,
   "y": 502.65,
   "width": 413.78,
   "size": 8
  },
  "TEAM": {
   "x": 153.07,
   "y": 488.34,
   "width": 413.78,
   "size": 8
  },
  "CART_NOTES": {
   "x": 153.07,
   "y": 474.04,
   "width": 413.78,
   "size": 8
  }
 }
};
